DeliveryDjango/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from DeliveryDjango import views
from DeliveryDjango.views import orders_chart_data, restaurants_rating_data, review_ratings_chart_data, \
    restaurant_list_view, restaurant_review_stats

from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from DeliveryDjango import views
#from DeliveryDjango.views import orders_chart_data, restaurants_rating_data, review_ratings_chart_data, restaurant_list_view, all_restaurants_review_stats, export_reviews_view

from DeliveryDjango.views import (
    orders_chart_data, restaurants_rating_data, review_ratings_chart_data,
    restaurant_list_view, restaurant_review_stats, all_restaurants_review_stats,
    export_reviews_view, export_reviews_to_excel, restaurants_with_reviews_stats, orders_by_restaurant_stats, review_counts_by_restaurant, top_restaurants_by_reviews  # Добавьте этот импорт
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register', views.register, name='register'),
    path('login', views.login_view, name='login'),
    path('', views.restaurant_list, name='restaurant_list'),
    path('restaurant/<int:restaurant_id>/', views.menu_restaurant, name='restaurant_menu'),
    path('dish_detail/<int:pk>/', views.DishDetail.as_view(), name='dish_detail_page'),
    path('add_to_cart/<int:dish_id>/', views.add_to_cart, name='add_to_cart'),
    path('view_cart/', views.view_cart, name='view_cart'),
    path('order/', views.order, name='order'),
    path('thank_you/', views.thank_you, name='thank_you'),
    path('logout', auth_views.LogoutView.as_view(next_page='restaurant_list'), name='logout'),
    path('user_orders/', views.user_orders, name='user_orders'),
    path('rate_order/<int:order_id>/', views.rate_order, name='rate_order'),
    path('api/orders-chart-data/', orders_chart_data, name='orders_chart_data'),
    path('api/restaurants-rating-data/', restaurants_rating_data, name='restaurants_rating_data'),
    path('restaurant_list/', restaurant_list_view, name='restaurant_list_view'),
    path('api/review-ratings-chart-data/<int:restaurant_id>/', review_ratings_chart_data, name='review_ratings_chart_data'),
    path('api/review-chart-data/<int:restaurant_id>/', restaurant_review_stats, name='review_chart_data'),
    path('admin/export_reviews/', export_reviews_view, name='export_reviews_view'),
    path('export/reviews/', export_reviews_to_excel, name='export_reviews_to_excel'),  # Убедитесь, что этот путь правильный
    path('api/all-restaurants-review-stats/', all_restaurants_review_stats, name='review_chart_data'),
    path('api/restaurants-with-reviews-stats/', restaurants_with_reviews_stats, name='restaurants_with_reviews_stats'),
    path('api/orders-by-restaurant-stats/', orders_by_restaurant_stats, name='orders_by_restaurant_stats'),
    path('api/review-counts-by-restaurant/<int:restaurant_id>/', review_counts_by_restaurant, name='review_counts_by_restaurant'),
    path('api/top-restaurants-by-reviews/', top_restaurants_by_reviews, name='top_restaurants_by_reviews'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

бэкап/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator


class Restaurant(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=100)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)


class MenuItem(models.Model):
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, decimal_places=2)


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    items = models.ManyToManyField(MenuItem, through='CartItem')


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)


class Order(models.Model):
    CART_CHOICES = [
        ('card', 'Карта'),
        ('cash', 'Наличные'),
    ]
    payment_method = models.CharField(max_length=20, choices=CART_CHOICES)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    items = models.ManyToManyField(CartItem, through='OrderItem')
    restaurant = models.ForeignKey(Restaurant, on_delete=models.SET_NULL, null=True)
    have_review = models.BooleanField(default=False)

    def __str__(self):
        return f"Order #{self.id}"

    def calculate_total_price(self):
        order_items = CartItem.objects.filter(cart__id=self.payment_method.split('_')[1])
        self.total_price = sum(order_item.item.price * order_item.quantity for order_item in order_items)
        self.save()

    def has_review_from_user(self, user):
        return self.reviews.filter(user=user).exists()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    cart_item = models.ForeignKey(CartItem, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        unique_together = ('order', 'cart_item',)


class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    middlename = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    pin = models.CharField(max_length=4)


class Review(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review_text = models.TextField()
    delivery_speed_rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    taste_intensity_rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    product_quality_rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

    def __str__(self):
        return f"{self.user.username}'s review for {self.order}"


class Category(models.Model):
    name = models.CharField(max_length=100)

templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Site{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'DeliveryDjango/bootstrap/css/bootstrap.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'DeliveryDjango/css/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.6.3.js"
            integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->
    <script src="{% static 'DeliveryDjango/bootstrap/js/bootstrap.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js"
            integrity="sha512-L0Shl7nXXzIlBSUUPpxrokqq4ojqgZFQczTYlGjzONGTDAcLremjwaWv5A+EDLnxhQzY5xUZPWLOLqYRkY0Cbw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto"> <!-- Добавлено ms-auto для правого выравнивания -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'restaurant_list' %}">Рестораны</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link button" href="{% url 'view_cart' %}">Корзина</a>
                    </li>
                    {% if request.user.is_anonymous %}
                        <!-- Отображаем кнопки для анонимных пользователей -->
                        <li class="nav-item">
                            <a class="nav-link btn btn-primary" href="{% url 'login' %}">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-success" href="{% url 'register' %}">Зарегистрироваться</a>
                        </li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'user_orders' %}">Мои заказы</a>
                        </li>
                        <!-- Отображаем кнопку для аутентифицированных пользователей -->
                        <li class="nav-item">
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Выйти</button>
                            </form>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<main role="main">
    {% block content %}
        <!-- Содержимое страницы будет вставлено здесь -->
    {% endblock %}
</main>

<footer>
    <!-- Подвал -->
</footer>
</body>
</html>

templates/cart.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container">
        <h1 class="my-4">Ваша корзина</h1>
        {% if cart_items %}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Название</th>
                    <th scope="col">Количество</th>
                    <th scope="col">Цена</th>
                </tr>
                </thead>
                <tbody>
                {% for cd in cart_items %}
                    <tr>
                        <td>{{ cd.item.title }}</td>
                        <td>{{ cd.quantity }}</td>
                        <td>{{ cd.item.price }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3">Ваша корзина пуста.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <p class="fs-4">Общая стоимость: {{ total_price }}</p>
            <a href="{% url 'order' %}" class="btn btn-primary">Оформить заказ</a>
        {% else %}
            <p class="fs-4">Ваша корзина пуста.</p>
        {% endif %}
    </div>
{% endblock %}

templates/dish_detail.html
{% extends 'base_generic.html' %}
{% load static %}
{% block content %}
    <div class="container card">
        <h1 class="pt-4">{{ dish.name }}</h1>
        <img class="img-fluid w-25" src="{{ dish.pic.url }}">
        <p>{{ dish.descr }}</p>
        <p>{{ dish.price }}</p>
        <button type="button" class="btn btn-primary">Добавить в корзину</button>
    </div>

{% endblock content %}

templates/login.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="center-screen">
    <div class="login-form">
        <h2 class="login-form-caption">{{ title }}</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="button-submit" type="submit" value="Войти">
        </form>
        <div class="button-submit" style="margin-top: 1em">
            <a href="{% url 'register' %}">Зарегистрироваться</a>
        </div>

    </div>
</div>

{% endblock %}

templates/order.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container">
        <h1 class="my-4">Оформление заказа</h1>
        <form method="post" class="row g-3">
            {% csrf_token %}
            <div class="col-md-6">
                <label for="{{ form.name.id_for_label }}" class="form-label">{{ form.name.label }}</label>
                <input type="text" name="{{ form.name.name }}" id="{{ form.name.id_for_label }}" class="form-control" value="{{ form.name.label }}" required>
            </div>
            <div class="col-md-6">
                <label for="{{ form.last_name.id_for_label }}" class="form-label">{{ form.last_name.label }}</label>
                <input type="text" name="{{ form.last_name.name }}" id="{{ form.last_name.id_for_label }}" class="form-control" value="{{ form.last_name.label }}" required>
            </div>
            <div class="col-md-6">
                <label for="{{ form.phone_number.id_for_label }}" class="form-label">{{ form.phone_number.label }}</label>
                <input type="text" name="{{ form.phone_number.name }}" id="{{ form.phone_number.id_for_label }}" class="form-control" value="{{ form.phone_number.label }}" required>
            </div>
            <div class="col-md-6">
                <label for="{{ form.address.id_for_label }}" class="form-label">{{ form.address.label }}</label>
                <input type="text" name="{{ form.address.name }}" id="{{ form.address.id_for_label }}" class="form-control" value="{{ form.address.label }}" required>
            </div>
            <div class="col-12">
                <label for="{{ form.payment_type.id_for_label }}" class="form-label">{{ form.payment_type.label }}</label>
                <select name="{{ form.payment_type.name }}" id="{{ form.payment_type.id_for_label }}" class="form-select" required>
                    {% for value, text in form.payment_type.field.choices %}
                        <option value="{{ value }}" {% if form.payment_type.value == value %}selected{% endif %}>{{ text }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Оформить заказ</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/rate_order.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <h1 class="my-4">Оценить заказ</h1>
    <form method="post" class="row g-3">
        {% csrf_token %}
        <div class="col-md-6">
            <label for="{{ form.review_text.id_for_label }}" class="form-label">{{ form.review_text.label }}</label>
            <input type="text" name="{{ form.review_text.name }}" id="{{ form.review_text.id_for_label }}" class="form-control" value="{{ form.review_text.value|default_if_none:'' }}" required>
        </div>
        <div class="col-md-6">
            <label for="{{ form.delivery_speed_rating.id_for_label }}" class="form-label">{{ form.delivery_speed_rating.label }}</label>
            <input type="number" name="{{ form.delivery_speed_rating.name }}" id="{{ form.delivery_speed_rating.id_for_label }}" class="form-control" value="{{ form.delivery_speed_rating.value|default_if_none:'' }}" min="1" max="5" required>
        </div>
        <div class="col-md-6">
            <label for="{{ form.taste_intensity_rating.id_for_label }}" class="form-label">{{ form.taste_intensity_rating.label }}</label>
            <input type="number" name="{{ form.taste_intensity_rating.name }}" id="{{ form.taste_intensity_rating.id_for_label }}" class="form-control" value="{{ form.taste_intensity_rating.value|default_if_none:'' }}" min="1" max="5" required>
        </div>
        <div class="col-md-6">
            <label for="{{ form.product_quality_rating.id_for_label }}" class="form-label">{{ form.product_quality_rating.label }}</label>
            <input type="number" name="{{ form.product_quality_rating.name }}" id="{{ form.product_quality_rating.id_for_label }}" class="form-control" value="{{ form.product_quality_rating.value|default_if_none:'' }}" min="1" max="5" required>
	</div>
        <div class="col-md-6">
            <label for="{{ form.service_quality_rating.id_for_label }}" class="form-label">{{ form.service_quality_rating.label }}</label>
            <input type="number" name="{{ form.service_quality_rating.name }}" id="{{ form.service_quality_rating.id_for_label }}" class="form-control" value="{{ form.service_quality_rating.value|default_if_none:'' }}" min="1" max="5" required>
        </div>
        <div class="col-18">
            <button type="submit" class="btn btn-primary">Оставить отзыв</button>
        </div>
    </form>
</div>
{% endblock %}

templates/register.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="d-flex justify-content-center mt-3">
        <h1 class="">Регистрация</h1>
    </div>
    <div class="center-screen">
        <div class="login-form">
            <h2 class="login-form-caption">{{ title }}</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="button-submit" type="submit" value="Зарегистрироваться">
            </form>
        </div>
    </div>
{% endblock %}

templates/restaurant_list.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <h1>Рестораны</h1>
        </div>
    </div>
    <div class="row">
        {% for restaurant in restaurants %}
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ restaurant.name }}</h5>
                    <p class="card-text">{{ restaurant.address }}</p>
                    <a class="btn btn-primary stretched-link" href="{% url 'restaurant_menu' restaurant.id %}">Посмотреть меню</a>
                </div>
            </div>
        </div>
        {% empty %}
            <div class="col-12 text-center p-4">
                <p>Нет доступных ресторанов.</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/restaurant_menu.html
{% extends 'base_generic.html' %}
{% block content %}
    <div class="container">
        <h1 class="text-center mb-4">Меню ресторана</h1>
        {% for category_name, dishes in grouped_dishes_by_category.items %}
            <div class="row">
                <div class="col-md-12 mb-4">
                    <h3>{{ category_name }}</h3>
                </div>
            </div>
            <div class="row">
                {% for dish in dishes %}
                    <div class="col-md-6 col-lg-4 col-xl-3 mb-4">
                        <div class="card h-100">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href="{% url 'dish_detail_page' dish.pk %}">{{ dish.title }}</a>
                                </h5>
                                <p class="card-text">{{ dish.descr }}</p>
                                <a href="{% url 'add_to_cart' dish.pk %}" class="btn btn-primary">Добавить в корзину</a>
                            </div>
                            <div class="card-footer bg-transparent border-top-0">
                                <span class="badge bg-primary rounded-pill">
                                    {% if dish.availability == 0 %}
                                        (Не доступно)
                                    {% else %}
                                        {{ dish.price }}
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/thank_you.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Спасибо за заказ</title>
    <style>
        body {
            margin: 0;
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: #f0f0f0; /* Светло-серый фон */
            font-family: Arial, sans-serif; /* Шрифт */
        }
        h1 {
            text-align: center; /* Центрирование текста */
            color: #333; /* Тёмно-серый цвет текста */
        }
    </style>
</head>
<body>
    <h1>Спасибо за заказ!</h1>
</body>
</html>

templates/user_orders.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <h2 class="my-4">Мои заказы</h2>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Дата заказа</th>
                <th scope="col">Способ оплаты</th>
                <th scope="col">Общая стоимость</th>
                <th scope="col">Отзыв</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order.created_at|date:"d.m.Y, H:i" }}</td>
                    <td>{{ order.get_payment_method_display }}</td>
                    <td>{{ order.total_price }}</td>
                    <td>
                        {% if order.have_review %}
                            Спасибо за отзыв
                        {% else %}
                            <a href="{% url 'rate_order' order.id %}" class="btn btn-sm btn-primary">Оценить</a>
                        {% endif %}
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">У вас пока нет заказов.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}